{{- if and .Values.notary.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "harbor.notary-server" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: notary
type: Opaque
data:
  {{- if not .Values.notary.secretName }}
  {{- $ca := genCA "harbor-notary-ca" 365 }}
  {{- $cert := genSignedCert (include "harbor.notary-signer" .) nil (list (include "harbor.notary-signer" .)) 365 $ca }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  {{- end }}
  {{- if or (eq (include "harbor.database.type" .) "mysql") (eq (include "harbor.database.type" .) "mariadb") }}
  server.json: {{ tpl (.Files.Get "conf/notary-server.mysql.json") . | b64enc }}
  signer.json: {{ tpl (.Files.Get "conf/notary-signer.mysql.json") . | b64enc }}
  {{- else }}
  server.json: {{ tpl (.Files.Get "conf/notary-server.json") . | b64enc }}
  signer.json: {{ tpl (.Files.Get "conf/notary-signer.json") . | b64enc }}
  {{- end }}
  NOTARY_SERVER_DB_URL: {{ include "harbor.database.notaryServer" . | b64enc }}
  NOTARY_SIGNER_DB_URL: {{ include "harbor.database.notarySigner" . | b64enc }}
{{- end }}
